### ISSUE TITLE
Docs missing how to render SVG instead of GIF

### ISSUE THREAD

**Issue by danbst** [katharostech/cast2gif#5]
Docs missing how to render SVG instead of GIF

**Comment by zicklag** [comment]
Currently cast2gif can't render SVG's. Initially cast2gif started out creating SVG representations of the terminal frames and then rendering them internally, but it turned out rather slow compared to manually rendering the fonts using the `fontkit` crate so I stopped using the SVG technique.

Even when it was using SVG, I never got it setup with animated SVG generation. If you need SVG output [term2svg](https://github.com/nbedos/termtosvg) works well. ( obviously not as convenient as having it in one tool, though ).

**Comment by zicklag** [comment]
It would be possible to bring back the SVG-based frame renderer, the start to which is still [in the codebase](https://github.com/katharostech/cast2gif/blob/master/src/frame_renderer/svg.rs), but I don't have the time for it myself.

**Comment by danbst** [comment]
Okay, I see. I was searching for SVG renderer, but I can stick with GIFs for now. Thanks for non-JS toolkit :)

**Comment by zicklag** [comment]
No problem. So glad it's helpful. :)
